### ISSUE TITLE
AGRP reports asset upload failed (spoiler: it did not)

### ISSUE THREAD

**Issue by jahunt1** [trevjonez/AndroidGithubReleasePlugin#1]
"Error updating policy"
![screen shot 2017-03-02 at 12 37 29 pm](https://cloud.githubusercontent.com/assets/8252819/23523790/7e165bf6-ff45-11e6-9962-8baa17d1b506.png)
![screen shot 2017-03-02 at 12 42 56 pm](https://cloud.githubusercontent.com/assets/8252819/23523953/0035e57a-ff46-11e6-8875-e84d2dbededf.png)

**Comment by simon1867** [comment]
So the apk got generated and uploaded to github, however it does fail to upload the build to Crashlytics.

**Comment by trevjonez** [comment]
Replying here with information from slack for tracking purposes. try using version `f84a3a7` and run your gradle invocations with `--info` so we can get more info from the failed request(s).

**Comment by trevjonez** [comment]
Any more occurrences of this?

**Comment by jahunt1** [comment]
Not since your last commit 👍

**Comment by trevjonez** [comment]
I am going to close this for now and blame it on network flake. If it happens more and you can provide some `--info` output I'll dig into it.
